services:
  - type: web
    name: alerta-segura
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn alerta_segura.wsgi:application"
    plan: free
  
